"""new settings and wb feedback table added

Revision ID: 21fa6edbe492
Revises: 38e5f90dd60f
Create Date: 2025-01-15 14:57:23.719533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '21fa6edbe492'
down_revision: Union[str, None] = '38e5f90dd60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wbfeedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feedback_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_valuation', sa.Integer(), nullable=False),
    sa.Column('with_photo', sa.Boolean(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reply', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wbfeedback_feedback_id'), 'wbfeedback', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_wbfeedback_product'), 'wbfeedback', ['product'], unique=False)
    op.create_index(op.f('ix_wbfeedback_sku'), 'wbfeedback', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wbfeedback_sku'), table_name='wbfeedback')
    op.drop_index(op.f('ix_wbfeedback_product'), table_name='wbfeedback')
    op.drop_index(op.f('ix_wbfeedback_feedback_id'), table_name='wbfeedback')
    op.drop_table('wbfeedback')
    # ### end Alembic commands ###
