"""removed wb feedback table

Revision ID: a01a51faf75d
Revises: 21fa6edbe492
Create Date: 2025-01-15 23:13:14.072629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a01a51faf75d'
down_revision: Union[str, None] = '21fa6edbe492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wbfeedback_feedback_id', table_name='wbfeedback')
    op.drop_index('ix_wbfeedback_product', table_name='wbfeedback')
    op.drop_index('ix_wbfeedback_sku', table_name='wbfeedback')
    op.drop_table('wbfeedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wbfeedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feedback_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_valuation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('with_photo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reply', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wbfeedback_pkey')
    )
    op.create_index('ix_wbfeedback_sku', 'wbfeedback', ['sku'], unique=False)
    op.create_index('ix_wbfeedback_product', 'wbfeedback', ['product'], unique=False)
    op.create_index('ix_wbfeedback_feedback_id', 'wbfeedback', ['feedback_id'], unique=True)
    # ### end Alembic commands ###
