"""wb_supplier_name added to user

Revision ID: 38e5f90dd60f
Revises: c8cd738f96a6
Create Date: 2025-01-15 03:00:20.629595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38e5f90dd60f'
down_revision: Union[str, None] = 'c8cd738f96a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wb_supplier_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_user_wb_supplier_name'), 'user', ['wb_supplier_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wb_supplier_name'), table_name='user')
    op.drop_column('user', 'wb_supplier_name')
    # ### end Alembic commands ###
